<a href="https://colab.research.google.com/github/Lakshmanaraja/Teaching-Deep-Learning/blob/main/Quickest_Matrix_Multiplication_using_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch import tensor


In [ ]:
a = torch.tensor([[3,4,5] ,[2,1,6], [1,2,3]])
b = torch.tensor([[4,5],[3,6],[1,8]])

In [ ]:
def matrixmulti_python(a,b):
  assert a.shape[1]==b.shape[0] # Number of columns in Matrix A should match Number of rows in Matrix B
  result = torch.zeros((a.shape[0],b.shape[1]))
  for i in range(a.shape[0]): #For each row of Matrix A
    for j in range(b.shape[1]): # For each column of Matrix B
      for k in range(b.shape[0]): # For each item value
          result[i,j] += a[i,k] * b[k,j]
  return result



In [ ]:

result = matrixmulti_python(a,b)
print(result)

%timeit -n 20 result1 = matrixmulti_python(a,b) 



tensor([[29., 79.],
        [17., 64.],
        [13., 41.]])
20 loops, best of 5: 313 µs per loop


In [ ]:
def matrixmulti_elementwise(a,b):
  assert a.shape[1]==b.shape[0] # Number of columns in Matrix A should match Number of rows in Matrix B
  result = torch.zeros((a.shape[0],b.shape[1]))
  for i in range(a.shape[0]): #For each row of Matrix A
    for j in range(b.shape[1]): # For each column of Matrix B
     # for k in range(b.shape[0]): # For each item value
          result[i,j] = (a[i] * b[:,j]).sum()
  return result

In [ ]:
result = matrixmulti_elementwise(a,b)
print( result )

%timeit -n 20 result1 = matrixmulti_elementwise(a,b) 

tensor([[29., 79.],
        [17., 64.],
        [13., 41.]])
20 loops, best of 5: 89.3 µs per loop


In [ ]:
def matrixmulti_broadcasting(a,b):
  result = torch.zeros((a.shape[0],b.shape[1]))
  assert a.shape[1]==b.shape[0] # Number of columns in Matrix A should match Number of rows in Matrix B
  for i in range(a.shape[0]): #For each row of Matrix A
    #for j in range(b.shape[1]): 
     # for k in range(b.shape[0]): 
    result[i]  = (a[i].unsqueeze(-1) * b).sum(dim=0)

  return result

In [ ]:
result = matrixmulti_broadcasting(a,b)
print ( result )

print( result )

%timeit -n 20 result1 = matrixmulti_broadcasting(a,b) 


tensor([[29., 79.],
        [17., 64.],
        [13., 41.]])
tensor([[29., 79.],
        [17., 64.],
        [13., 41.]])
20 loops, best of 5: 41.9 µs per loop


In [ ]:
def matrixmulti_einstein_summation(a,b): return torch.einsum('ik,kj->ij',a,b)

In [ ]:
result = matrixmulti_einstein_summation(a,b)
print( result )
%timeit -n 20 result1 = matrixmulti_broadcasting(a,b) 

tensor([[29, 79],
        [17, 64],
        [13, 41]])
20 loops, best of 5: 51.3 µs per loop


In [ ]:
def matrixmulti_at_operator(a,b): 
  return a@b

In [ ]:
result = matrixmulti_at_operator(a,b)
print ( result )
%timeit -n 20 result1 = matrixmulti_at_operator(a,b) 

tensor([[29, 79],
        [17, 64],
        [13, 41]])
The slowest run took 14.03 times longer than the fastest. This could mean that an intermediate result is being cached.
20 loops, best of 5: 3.69 µs per loop


In [ ]:
%timeit -n 20 result1 = matrixmulti_python(a,b) 
%timeit -n 20 result2 = matrixmulti_elementwise(a,b) 
%timeit -n 20 result3 = matrixmulti_broadcasting(a,b)
%timeit -n 20 result4 = matrixmulti_einstein_summation(a,b) 
%timeit -n 20 result5 = a@b

20 loops, best of 5: 314 µs per loop
20 loops, best of 5: 90.7 µs per loop
20 loops, best of 5: 41.5 µs per loop
20 loops, best of 5: 15.6 µs per loop
20 loops, best of 5: 2.39 µs per loop
